// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoYxR3jGNQot-Z_EXgKt_Gq9UoECk6tvs',
    appId: '1:592669699882:web:58bd34b38e656530a7f853',
    messagingSenderId: '592669699882',
    projectId: 'issueflow-app',
    authDomain: 'issueflow-app.firebaseapp.com',
    storageBucket: 'issueflow-app.firebasestorage.app',
    measurementId: 'G-KGMCBHF0BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt5vpuwqcJ-t3Vo1dlBTEQQ1e6iBV5fNk',
    appId: '1:592669699882:android:ee543944c54a4ccfa7f853',
    messagingSenderId: '592669699882',
    projectId: 'issueflow-app',
    storageBucket: 'issueflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMXB66KgCUp23s5WFeQNGPQakty6dIV8I',
    appId: '1:592669699882:ios:9a495ea07505d063a7f853',
    messagingSenderId: '592669699882',
    projectId: 'issueflow-app',
    storageBucket: 'issueflow-app.firebasestorage.app',
    iosClientId: '592669699882-u0rm7fdm2svsu5htmseld3grqpbefnud.apps.googleusercontent.com',
    iosBundleId: 'com.example.issueflowFronted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMXB66KgCUp23s5WFeQNGPQakty6dIV8I',
    appId: '1:592669699882:ios:9a495ea07505d063a7f853',
    messagingSenderId: '592669699882',
    projectId: 'issueflow-app',
    storageBucket: 'issueflow-app.firebasestorage.app',
    iosClientId: '592669699882-u0rm7fdm2svsu5htmseld3grqpbefnud.apps.googleusercontent.com',
    iosBundleId: 'com.example.issueflowFronted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoYxR3jGNQot-Z_EXgKt_Gq9UoECk6tvs',
    appId: '1:592669699882:web:435ec6f60e168251a7f853',
    messagingSenderId: '592669699882',
    projectId: 'issueflow-app',
    authDomain: 'issueflow-app.firebaseapp.com',
    storageBucket: 'issueflow-app.firebasestorage.app',
    measurementId: 'G-Y37BYT6GZ8',
  );
}
